const express = require('express')
const router = express.Router()
const {upload} = require('../config/cloudinaryConfig')


const register = require('../controllers/sesion/registerControler')
const login = require('../controllers/sesion/loginController')
const userDetails = require('../controllers/profiles/userdetailsController')
const updateProfile = require('../controllers/profiles/updateProfileController')
const center = require('../controllers/center/centerController')
const getKidParents = require('../controllers/linkeds/getKidParentsCotroller')
const getKidTeachers = require('../controllers/linkeds/getKidTeachersController')
const getKid = require('../controllers/profiles/getKidController')
const linkedKidParents = require('../controllers/linkeds/linkedKidParentsController')
const linkedKidTeachers = require('../controllers/linkeds/linkedKidTeachersController')
const addOrUpdateKidProfile = require('../controllers/profiles/addOrUpdateKidProfileController')
const insertParentsDiary = require('../controllers/diary/insertParentsDiaryController')
const insertTeachersDiary = require('../controllers/diary/insertTeachersDiaryController')
const getDiaryForteachers = require('../controllers/diary/getDiaryForTeachersController')
const getDiaryForParents = require('../controllers/diary/getDiaryForParentsController')
const getEventsForKid = require('../controllers/events/getEventsForKidController')
const getEventsForTeacher = require('../controllers/events/getEventsForTeacherController')
const addEvent =  require('../controllers/events/addEventController')
const linkedEventsKids = require('../controllers/events/linkedEventsKidsController')
const addBook = require('../controllers/books/addBookController')
const getBooks = require('../controllers/books/getBooksController')
const getDevelopmentalMilestones = require('../controllers/milestones/getDevelopmentalMilestonesController')
const getMilestonesForKid = require('../controllers/milestones/getMilestonesForKidController')
const saveMilestonesForKid = require('../controllers/milestones/saveMilestonesForKidController')
const saveGoal = require('../controllers/goals/saveGoalController')
const getGoalsForKid = require('../controllers/goals/getGoalsForKidController')
const updateGoalState = require('../controllers/goals/updateGoalsController')
const addAssessmentForKid = require('../controllers/assessment/addAssessmentController')
const getAssessmentForKid = require('../controllers/assessment/getAssessmentController')
const saveHeight = require('../controllers/growthCharts/saveNewHeightController')
const saveWeight = require('../controllers/growthCharts/saveNewWeightController')
const getHeight = require('../controllers/growthCharts/getHeightForKidController')
const getWeight = require('../controllers/growthCharts/getWeightForKidController')
const deleteHeight = require('../controllers/growthCharts/deleteHeightController')
const deleteWeight = require('../controllers/growthCharts/deteleWeightController')
const addAllergies = require('../controllers/allergies/addAllergiesController')
const getAllergies = require('../controllers/allergies/getAllergiesController')
const addCondition = require('../controllers/medicalConditions/addConditionController')
const getConditions = require('../controllers/medicalConditions/getConditionsController')
const addFood = require('../controllers/feeding/addFoodController')
const getFoods = require('../controllers/feeding/getFoodController')
const addImageForKid = require('../controllers/gallery/saveImageForKidController')
const getImagesForKid = require('../controllers/gallery/getImagesForKidController')
const uploadFile = require('../controllers/adminDocuments/uploadDocumentController')
const uploadKidFile = require('../controllers/adminDocuments/uploadKidDocumentController')
const getDocumentById = require('../controllers/adminDocuments/getDocumentByIdController')
const getDocumentByLink = require('../controllers/adminDocuments/getDocumentByLinkController')
const deleteDocument = require('../controllers/adminDocuments/deleteDocumentController')
const virtualAssintant = require('../controllers/virtualAssistant/virtualAssistantController')


router.post('/register', register);
router.post('/login', login);
router.get('/detalleUsuario/:userId/:perfil', userDetails)
router.post('/updateProfile', updateProfile)
router.get('/centros', center)
router.get('/ninos_padres/:idProgenitor', getKidParents)
router.get('/ninos_educadores/:idEducador', getKidTeachers)
router.get('/contextokid/:kidId', getKid)
router.post('/linkednino_progenitor', linkedKidParents)
router.post('/linkednino_educador', linkedKidTeachers)
router.post('/datosninos', addOrUpdateKidProfile)
router.post('/diario_progenitores/insertar', insertParentsDiary)
router.post('/diario_educadores/insertar', insertTeachersDiary)
router.get('/diario_para_educadores/:idKid', getDiaryForteachers)
router.get('/diario_para_progenitores/:idKid', getDiaryForParents)
router.get('/eventos_nino/:idNino', getEventsForKid)
router.get('/eventos_educador/:id_educador', getEventsForTeacher)
router.get('/events', addEvent)
router.post('/eventos_nino', linkedEventsKids)
router.post('/addBook', upload.single('imagen_url'), addBook)
router.get('/books', getBooks)
router.get('/getmilestones', getDevelopmentalMilestones)
router.get('/getMilestonesForKid/:idKid', getMilestonesForKid)
router.post('/saveMilestoneForKid', saveMilestonesForKid)
router.post('/saveGoal', saveGoal)
router.get('/getGoals/:idKid', getGoalsForKid)
router.put('/updateGoal/:goalId', updateGoalState)
router.post('/addAssessment', addAssessmentForKid)
router.get('/getAssessment/:idKid', getAssessmentForKid)
router.post('/addWeight', saveWeight)
router.post('/addHeight', saveHeight)
router.get('/getWeightsForKid/:idKid', getWeight)
router.get('/getHeightsForKid/:idKid', getHeight)
router.delete('/deleteHeight/:id', deleteHeight)
router.delete('/deleteWeight/:id', deleteWeight)
router.post('/addAllergen', addAllergies)
router.get('/getAllergens/:id', getAllergies)
router.post('/addMedicalCondition', addCondition)
router.get('/getConditions/:id', getConditions)
router.post('/addFood', addFood)
router.get('/getFoods/:id', getFoods)
router.post('/addImage',upload.single('imagen'), addImageForKid)
router.get('/getImages/:idKid', getImagesForKid)
router.post('/addDocument',upload.single('documento'), uploadFile)
router.post('/addDocumentForKid', upload.single('documento'), uploadKidFile)
router.get('/getDocumentById/:id/:type', getDocumentById)
router.get('/getDocumentByLink/:id/:type', getDocumentByLink)
router.delete('/deleteDocument/:id/:type', deleteDocument)
router.post('/virtualAssistant', virtualAssintant)

module.exports = router

